Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data type of variables list_ and array_list.

The variable list_ is a Python list, which can hold elements of different data types. In this case, it appears to be a list of strings.

The variable array_list is a NumPy array, created using the np.array() function. NumPy arrays are homogeneous, meaning they can only hold elements of a single data type. In this case, since the input list contains strings, the elements in the NumPy array will be of the string data type.

To print the data types of both variables, you can use the type() function. Here's the code:

In [25]:
import numpy as np
list_ =  [ '1' , '2' , '3' , '4' , '5' ] 
array_list = np.array(object = list_)

print("Data Type of list_ is : ",type(list_))
print("Data Type of array_list is : ",type(array_list))

Data Type of list_ is :  <class 'list'>
Data Type of array_list is :  <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [26]:
import numpy as np
list_ =  [ '1' , '2' , '3' , '4' , '5' ] 
array_list = np.array(object = list_)

print("Data Type of element in list_ are ")
for element in list_:
     print(type(element))
   
print("\nData Type of element in array_list are ")
for element in array_list:
    print(type(element))

Data Type of element in list_ are 
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data Type of element in array_list are 
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [28]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

array_list = np.array(object=num_list, dtype=int)


In this case, there won't be any difference in the data types of the elements present in both the variables num_list and num_array. The reason is that the elements in num_list are already integers.

To print the data types of each element in both num_list and array_list, you can use the type() function within nested loops. Here's the updated code:

In [29]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

array_list = np.array(object=num_list, dtype=int)

print("Data types of elements in num_list:")
for sublist in num_list:
    for element in sublist:
        print(type(element))

print("\nData types of elements in array_list:")
for sublist in array_list:
    for element in sublist:
        print(type(element))


Data types of elements in num_list:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


You'll see that the elements in both num_list and array_list are integers (int data type).

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [30]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# Finding the shape of num_array
shape = num_array.shape

# Finding the size of num_array
size = num_array.size

print("Shape of num_array:", shape)
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


The shape (2, 3) indicates that num_array has 2 rows and 3 columns. The size 6 represents the total number of elements in num_array.

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [32]:
numpy_array = np.zeros((3,3))

In [34]:
print(numpy_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [36]:
import numpy as np

identity_matrix = np.ones(5)

print(identity_matrix)


[1. 1. 1. 1. 1.]


In [41]:
print(np.diag(identity_matrix))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
